[build]
  # Affiche la version Node, les variables Vite et lance Vite en mode debug
  command = "node -e \"console.log('Node',process.version);console.log('VITE_SUPABASE_URL?',!!process.env.VITE_SUPABASE_URL);console.log('VITE_SUPABASE_ANON_KEY?',!!process.env.VITE_SUPABASE_ANON_KEY)\" && npm run build -- --debug"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS    = "--no-audit --no-fund --loglevel=error"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
